INSERT INTO status_codes (entity_type, status, description) VALUES
('USER', 'ACTIVE', 'Account is active'),
('USER', 'INACTIVE', 'Account is temporarily locked'),
('USER', 'BANNED', 'Account is permanently banned'),
('USER', 'UNVERIFIED', 'Account has not been verified (email verification needed)'),
('EVENT', 'DRAFT', 'Event is in draft status, not yet published'),
('EVENT', 'PUBLISHED', 'Event has been published and is open for registration'),
('EVENT', 'ONGOING', 'Event is currently in progress'),
('EVENT', 'COMPLETED', 'Event has finished'),
('EVENT', 'CANCELED', 'Event has been canceled'),
('EVENT', 'POSTPONED', 'Event has been postponed'),
('TICKET', 'AVAILABLE', 'Ticket is currently available for purchase'),
('TICKET', 'SOLD_OUT', 'Ticket is sold out'),
('TICKET', 'RESERVED', 'Ticket is currently reserved (pending payment)'),
('TICKET', 'CANCELED', 'Ticket has been canceled'),
('PAYMENT', 'PENDING', 'Transaction is pending processing'),
('PAYMENT', 'SUCCESSFUL', 'Transaction is successful'),
('PAYMENT', 'FAILED', 'Transaction failed'),
('PAYMENT', 'REFUNDED', 'Transaction has been refunded'),
('TICKET_QR_CODES', 'ACTIVE', 'QR code is active and can be used for check-in'),
('TICKET_QR_CODES', 'USED', 'QR code has already been used'),
('TICKET_QR_CODES', 'EXPIRED', 'QR code has expired'),
('EVENT_PARTICIPANTS', 'REGISTERED', 'User has registered for the event'),
('EVENT_PARTICIPANTS', 'CONFIRMED', 'User''s participation has been confirmed'),
('EVENT_PARTICIPANTS', 'CHECKED_IN', 'User has checked in at the event'),
('EVENT_PARTICIPANTS', 'CANCELED', 'User has canceled their registration');